// data.ts - Our fake backend data store

import { User, Category, Thread } from "./store";

// Sample Users
export const users: User[] = [
    {
        id: "user-1",
        username: "alex_dev",
        avatarUrl: "/api/placeholder/32/32",
        joinDate: "2023-09-15",
        karma: 1542,
        bio: "Full-stack developer passionate about React and TypeScript",
        interests: ["tech", "programming", "gaming"]
    },
    {
        id: "user-2",
        username: "sophia_design",
        avatarUrl: "/api/placeholder/32/32",
        joinDate: "2023-10-02",
        karma: 873,
        bio: "UI/UX designer with a love for minimalism",
        interests: ["design", "art", "photography"]
    },
    {
        id: "user-3",
        username: "max_gamer",
        avatarUrl: "/api/placeholder/32/32",
        joinDate: "2024-01-18",
        karma: 341,
        interests: ["gaming", "tech", "music"]
    },
    {
        id: "user-4",
        username: "emma_code",
        avatarUrl: "/api/placeholder/32/32",
        joinDate: "2023-08-05",
        karma: 2104,
        bio: "Backend developer specializing in Node.js and databases",
        interests: ["programming", "tech", "science"]
    },
    {
        id: "user-5",
        username: "david_music",
        avatarUrl: "/api/placeholder/32/32",
        joinDate: "2024-02-20",
        karma: 127,
        interests: ["music", "art", "literature"]
    }
];

// Sample Categories
export const categories: Category[] = [
    {
        id: "cat-1",
        name: "Technology",
        description: "Discussions about the latest in tech and gadgets",
        icon: "Laptop",
        color: "bg-gray-500",
        threadCount: 127,
        slug: "technology"
    },
    {
        id: "cat-2",
        name: "Programming",
        description: "Share code, ask questions, discuss languages and frameworks",
        icon: "Code",
        color: "bg-green-600",
        threadCount: 248,
        slug: "programming"
    },
    {
        id: "cat-3",
        name: "Gaming",
        description: "Everything related to video games, from AAA to indie",
        icon: "Gamepad2",
        color: "bg-purple-600",
        threadCount: 195,
        slug: "gaming"
    },
    {
        id: "cat-4",
        name: "Design",
        description: "UI/UX design, graphic design, and visual arts",
        icon: "Palette",
        color: "bg-pink-500",
        threadCount: 86,
        slug: "design"
    },
    {
        id: "cat-5",
        name: "Music",
        description: "Discuss artists, genres, instruments, and music theory",
        icon: "Music",
        color: "bg-red-500",
        threadCount: 104,
        slug: "music"
    },
    {
        id: "cat-6",
        name: "Science",
        description: "Scientific discussions, research, and discoveries",
        icon: "Atom",
        color: "bg-amber-500",
        threadCount: 73,
        slug: "science"
    },
    {
        id: "cat-7",
        name: "Literature",
        description: "Books, writing, poetry, and literary discussions",
        icon: "BookOpen",
        color: "bg-emerald-600",
        threadCount: 63,
        slug: "literature"
    },
    {
        id: "cat-8",
        name: "Photography",
        description: "Photography techniques, gear, and sharing photos",
        icon: "Camera",
        color: "bg-indigo-600",
        threadCount: 58,
        slug: "photography"
    },
    {
        id: "cat-9",
        name: "Artificial Intelligence",
        description: "AI, machine learning, and deep learning discussions",
        icon: "Brain",
        color: "bg-blue-600",
        threadCount: 92,
        slug: "artificial-intelligence"
    },
    {
        id: "cat-10",
        name: "Cybersecurity",
        description: "Security best practices, tools, and threat analysis",
        icon: "Shield",
        color: "bg-red-600",
        threadCount: 67,
        slug: "cybersecurity"
    },
    {
        id: "cat-11",
        name: "DevOps",
        description: "DevOps practices, CI/CD, and infrastructure",
        icon: "Server",
        color: "bg-orange-500",
        threadCount: 84,
        slug: "devops"
    },
    {
        id: "cat-12",
        name: "Mobile Development",
        description: "iOS, Android, and cross-platform development",
        icon: "Smartphone",
        color: "bg-teal-500",
        threadCount: 76,
        slug: "mobile-development"
    }
];

// Sample Threads
export const threads: Thread[] = [
    {
        id: "thread-1",
        title: "React 19 features discussion",
        content: "What are your thoughts on the new features introduced in React 19? I'm particularly excited about the improved server components and the new hooks.",
        categoryId: "cat-2",
        authorId: "user-1",
        createdAt: "2025-03-15T14:35:00Z",
        updatedAt: "2025-03-15T14:35:00Z",
        upvotes: 42,
        downvotes: 3,
        views: 187,
        tags: ["react", "javascript", "frontend"],
    },
    {
        id: "thread-2",
        title: "Best design tools in 2025",
        content: "I'm looking to update my design toolkit. What are the best design tools you're using in 2025? I currently use Figma but wondering if there are better alternatives now.",
        categoryId: "cat-4",
        authorId: "user-2",
        createdAt: "2025-03-18T09:12:00Z",
        updatedAt: "2025-03-19T16:45:00Z",
        upvotes: 38,
        downvotes: 1,
        views: 156,
        tags: ["design", "tools", "UI/UX"],
    },
    {
        id: "thread-3",
        title: "The state of gaming in 2025",
        content: "How do you feel about the direction of gaming in 2025? With VR becoming more mainstream and cloud gaming services improving, what trends are you most excited about?",
        categoryId: "cat-3",
        authorId: "user-3",
        createdAt: "2025-03-20T18:24:00Z",
        updatedAt: "2025-03-20T18:24:00Z",
        upvotes: 56,
        downvotes: 8,
        views: 224,
        tags: ["gaming", "VR", "future tech"],
    },
    {
        id: "thread-4",
        title: "Advanced PostgreSQL optimization techniques",
        content: "I'm working on optimizing a large PostgreSQL database for a high-traffic application. What are some advanced optimization techniques you've found effective?",
        categoryId: "cat-2",
        authorId: "user-4",
        createdAt: "2025-03-12T11:05:00Z",
        updatedAt: "2025-03-14T08:30:00Z",
        upvotes: 78,
        downvotes: 2,
        views: 321,
        tags: ["database", "postgresql", "performance"],
    },
    {
        id: "thread-5",
        title: "Album recommendations for concentrated work",
        content: "I'm looking for instrumental music albums that help with concentration during coding sessions. Any recommendations?",
        categoryId: "cat-5",
        authorId: "user-5",
        createdAt: "2025-03-22T15:17:00Z",
        updatedAt: "2025-03-22T15:17:00Z",
        upvotes: 32,
        downvotes: 4,
        views: 142,
        tags: ["music", "productivity", "instrumental"],
    },
    {
        id: "thread-6",
        title: "New breakthroughs in quantum computing",
        content: "Did anyone catch the recent paper on quantum error correction? It seems like we might be closer to practical quantum computers than previously thought.",
        categoryId: "cat-6",
        authorId: "user-1",
        createdAt: "2025-03-10T07:45:00Z",
        updatedAt: "2025-03-10T07:45:00Z",
        upvotes: 65,
        downvotes: 3,
        views: 198,
        tags: ["quantum", "computing", "science"],
    },
    {
        id: "thread-7",
        title: "Must-read sci-fi novels of the decade",
        content: "I'm looking to expand my sci-fi reading list. What are some must-read novels from the past decade that explore interesting technological or societal concepts?",
        categoryId: "cat-7",
        authorId: "user-3",
        createdAt: "2025-03-08T19:28:00Z",
        updatedAt: "2025-03-09T10:15:00Z",
        upvotes: 47,
        downvotes: 5,
        views: 174,
        tags: ["books", "sci-fi", "literature"],
    },
    {
        id: "thread-8",
        title: "Favorite camera setups for street photography",
        content: "Street photographers, what's your current camera setup? I'm debating between upgrading to a newer mirrorless or sticking with my trusty DSLR.",
        categoryId: "cat-8",
        authorId: "user-2",
        createdAt: "2025-03-16T12:33:00Z",
        updatedAt: "2025-03-16T12:33:00Z",
        upvotes: 29,
        downvotes: 2,
        views: 113,
        tags: ["photography", "gear", "street"],
    },
    {
        id: "thread-9",
        title: "The best way to learn React",
        content: "I'm new to React and I'm looking for the best way to learn it. What are some resources you recommend?",
        categoryId: "cat-2",
        authorId: "user-1",
        createdAt: "2025-03-11T15:40:00Z",
        updatedAt: "2025-03-11T15:40:00Z",
        upvotes: 34,
        downvotes: 4,
        views: 165,
        tags: ["react", "learning", "resources"],
        parentId: "thread-1",
    },
    {
        id: "thread-10",
        title: "Latest developments in GPT-5",
        content: "What are your thoughts on the recent GPT-5 developments? The multi-modal capabilities seem particularly promising for creative applications.",
        categoryId: "cat-9",
        authorId: "user-4",
        createdAt: "2025-03-23T10:15:00Z",
        updatedAt: "2025-03-23T10:15:00Z",
        upvotes: 89,
        downvotes: 12,
        views: 245,
        tags: ["AI", "GPT-5", "machine learning"],
    },
    {
        id: "thread-11",
        title: "Zero-trust security architecture",
        content: "I'm implementing a zero-trust security model for our microservices architecture. Any tips or best practices to share?",
        categoryId: "cat-10",
        authorId: "user-1",
        createdAt: "2025-03-21T13:45:00Z",
        updatedAt: "2025-03-22T09:20:00Z",
        upvotes: 45,
        downvotes: 3,
        views: 178,
        tags: ["security", "zero-trust", "architecture"],
    },
    {
        id: "thread-12",
        title: "GitOps workflow with ArgoCD",
        content: "Has anyone successfully implemented GitOps using ArgoCD? I'm looking for real-world examples and lessons learned.",
        categoryId: "cat-11",
        authorId: "user-4",
        createdAt: "2025-03-19T16:30:00Z",
        updatedAt: "2025-03-19T16:30:00Z",
        upvotes: 67,
        downvotes: 5,
        views: 212,
        tags: ["gitops", "argocd", "devops"],
    },
    {
        id: "thread-13",
        title: "Flutter vs React Native in 2025",
        content: "What are your experiences with Flutter and React Native in 2025? Which one would you recommend for a new cross-platform project?",
        categoryId: "cat-12",
        authorId: "user-1",
        createdAt: "2025-03-17T11:20:00Z",
        updatedAt: "2025-03-18T14:15:00Z",
        upvotes: 92,
        downvotes: 15,
        views: 289,
        tags: ["mobile", "flutter", "react-native"],
    },
    {
        id: "thread-14",
        title: "Best practices for AI model deployment",
        content: "What are the current best practices for deploying ML models in production? I'm particularly interested in monitoring and scaling strategies.",
        categoryId: "cat-9",
        authorId: "user-4",
        createdAt: "2025-03-16T09:45:00Z",
        updatedAt: "2025-03-16T09:45:00Z",
        upvotes: 78,
        downvotes: 8,
        views: 234,
        tags: ["AI", "deployment", "MLOps"],
    },
    {
        id: "thread-15",
        title: "Container security scanning tools",
        content: "What container security scanning tools are you using in your CI/CD pipeline? Looking for recommendations for vulnerability scanning.",
        categoryId: "cat-10",
        authorId: "user-1",
        createdAt: "2025-03-15T14:20:00Z",
        updatedAt: "2025-03-15T14:20:00Z",
        upvotes: 56,
        downvotes: 4,
        views: 167,
        tags: ["security", "containers", "devops"],
    }
];
